name: Create Deployment Event

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Create "pending" deployment on GitHub
  # (Moved to a separate job to avoid github-actions inactive deployment. See: https://github.com/actions/runner/issues/1001)
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production